name: Re-building Docker
on:
  push:
    branches: [main]
    paths:
      - 'environment_setup/**'
  workflow_dispatch:

env:
  RESOURCE_GROUP: mlops-rg
  WORKSPACE: azure-ml-toyota-demo

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ./environment_setup/
          tags: |
            ghcr.io/ghcr.io/lukas-lundmark/mlops-ci-image:latest
            ghcr.io/ghcr.io/lukas-lundmark/mlops-ci-image:${{ github.sha }}

          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
